<a href="https://colab.research.google.com/github/Leitich/Artificial-Intelligence/blob/main/task1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [179]:
import pandas as pd #dataset library
import numpy as np #linear algebra library

In [180]:
from numpy import array
from sklearn.preprocessing import Normalizer
from keras.activations import sigmoid
from keras.losses import mse
from numpy.random import uniform,normal 

Hyperparameters

In [181]:
batch_size=2

In [182]:
data_dict={'Day 1':[30,40,50,20,15,60],'Day 2':[40,50,20,15,60,70],
           'Day 3':[50,20,15,60,70,50],'Target':[20,15,60,70,50,40]}

In [183]:
data=pd.DataFrame(data_dict)

In [184]:
data


Day 1  Day 2  Day 3  Target
0     30     40     50      20
1     40     50     20      15
2     50     20     15      60
3     20     15     60      70
4     15     60     70      50
5     60     70     50      40

In [185]:
X=data.drop('Target',axis=1)
y=data['Target']

In [186]:
X_trans=Normalizer(norm='max').fit_transform(X)

In [187]:
np.reshape(array(Y),(1,-1))

array([[0.1568661 , 0.20915479, 0.26144349, 0.20915479, 0.26144349,
        0.1045774 , 0.26144349, 0.1045774 , 0.07843305, 0.1045774 ,
        0.07843305, 0.31373219, 0.07843305, 0.31373219, 0.36602089,
        0.31373219, 0.36602089, 0.26144349]])

In [188]:
Y=Normalizer().fit_transform(np.reshape(array(X),(1,-1)))

In [189]:
Y

array([[0.1568661 , 0.20915479, 0.26144349, 0.20915479, 0.26144349,
        0.1045774 , 0.26144349, 0.1045774 , 0.07843305, 0.1045774 ,
        0.07843305, 0.31373219, 0.07843305, 0.31373219, 0.36602089,
        0.31373219, 0.36602089, 0.26144349]])

In [190]:
X_trans

array([[0.6       , 0.8       , 1.        ],
       [0.8       , 1.        , 0.4       ],
       [1.        , 0.4       , 0.3       ],
       [0.33333333, 0.25      , 1.        ],
       [0.21428571, 0.85714286, 1.        ],
       [0.85714286, 1.        , 0.71428571]])

ANN Model From Scratch

In [191]:
"""weight_1=array([[.2,.1],[.3,.1],[.2,.1]])
weight_2=array([[.5],[.1]])"""

weight_1=

In [192]:
X=X_trans

In [199]:
X[0:batch_size]

array([[0.6, 0.8, 1. ],
       [0.8, 1. , 0.4]])

In [194]:
output_1=X[0:batch_size]@weight_1
output_1

array([[0.56, 0.24],
       [0.54, 0.22]])

In [195]:
act_output_1=sigmoid(output_1).numpy()
act_output_1

array([[0.63645254, 0.55971365],
       [0.63181242, 0.55477924]])

In [196]:
final_output=act_output_1@weight_2
final_output

array([[0.37419764],
       [0.37138413]])

In [202]:
y_true=Y[0][0:batch_size]
y_pred=final_output.T[0]

In [203]:
y_true

array([0.1568661 , 0.20915479])

In [205]:
y_pred.T

array([0.37419764, 0.37138413])

Computing Mean Squared Error

In [ ]:
mse(y_true,y_pred)